### ISSUE TITLE
Disk Usage Meter Alignment

### ISSUE THREAD

**Issue by IonicOwl** [EnhancedJax/Plainext#1]
Hi, I've been trying to fix a visual issue where the meters for disk usage don't line up with the meters for CPU/RAM/GPU, as shown below:

![image](https://user-images.githubusercontent.com/36578130/120907105-d7816280-c656-11eb-88dd-361c1059c223.png)

I'm using the Overview style, but this misalignment also exists in the main style too (though I haven't attempted to modify that one).  It looks as though an additional trailing space needs adding after each drive label, so I went into @Resources/Styles/Overview.inc and added these in on line 37.  This lines everything up after a refresh, but the accent is no longer working:

![image](https://user-images.githubusercontent.com/36578130/120907217-b10ff700-c657-11eb-9ca3-3d9768ac5b0d.png)

I've tried adding the space before the drive label, Rainmeter ignores it.  I also tried adding the space before the colon, but that also breaks it.  Is there anything that can be done to correct the misalignment without breaking the functionality of the meter?

**Comment by EnhancedJax** [comment]
Hey, sorry I didn't notice the misalignment. For your modification did you edit the regex under the text option? You'll have to add the same trailing spaces to that

**Comment by IonicOwl** [comment]
As far as I know, I haven't edited any Regex, not too familiar with it myself.  All I did was add a space after the "C:" and "D:" parts of the line.  Is there something else I have to change somethere?

**Comment by EnhancedJax** [comment]
`[ResourceGraphDrives]
Text=C:  //////////////////// [DriveCPercent:1]%#CRLF#D:  //////////////////// [DriveDPercent:1]%
InlinePattern3=C:  (\/{[DriveCActual:0]}).*
InlinePattern4=D:  (\/{[DriveDActual:0]}).*
`
Replace ResourceGraphDrives with this in the Overview.inc in folder Styles.

**Comment by IonicOwl** [comment]
That did the trick!  Thank you very much :)
