### ISSUE TITLE
Drive Status lines use wrong color

### ISSUE THREAD

**Issue by Chuckle12345** [EnhancedJax/Plainext#2]
If I only have 2 drives, both drive status lines are white.  If I add more drives the second and 3rd drive status lines change color.  I have tried numerous variations.  I have repeated the second entry to ensure the syntax is correct, and color still changes.  I love the skin but this is eating my lunch.  Any assistance you could offer would be much appreciated.  I am also including the lines from Main.ini.  You will see the original line commented out.

[ResourceGraphDrives]
Meter=String
Autoscale=1
MeasureName=DriveCFree
MeasureName2=DriveCTotal
MeasureName3=MeasureDriveCRead
MeasureName4=MeasureDriveCWrite
MeasureName5=DriveDFree
MeasureName6=DriveDTotal
MeasureName7=MeasureDriveDRead
MeasureName8=MeasureDriveDWrite
MeasureName9=DriveEFree
MeasureName10=DriveETotal
MeasureName11=MeasureDriveERead
MeasureName12=MeasureDriveEWrite
MeasureName13=DriveHFree
MeasureName14=DriveHTotal
MeasureName15=MeasureDriveHRead
MeasureName16=MeasureDriveHWrite
MeasureName17=DriveZFree
MeasureName18=DriveZTotal
MeasureName19=MeasureDriveZRead
MeasureName20=MeasureDriveZWrite
;Text=C: //////////////////// [DriveCPercent:1]%#CRLF#F: %1B T: %2B | R: %3 W: %4#CRLF#D: //////////////////// [DriveDPercent:1]%#CRLF#F: %5B T: %6B | R: %7 W: %8
Text=C: //////////////////// [DriveCPercent:1]% (Windows)#CRLF#F: %1B T: %2B | R: %3 W: %4#CRLF#D: //////////////////// [DriveDPercent:1]% (Virtual)#CRLF#F: %5B T: %6B | R: %7 W: %8#CRLF#E: //////////////////// [DriveEPercent:1]% (UHaul)#CRLF#F: %9B T: %10B | R: %11 W: %12#CRLF#H: //////////////////// [DriveHPercent:1]% (RAMDisk)#CRLF#F: %13B T: %14B | R: %15 W: %16#CRLF#Z: //////////////////// [DriveZPercent:1]% (NAS)#CRLF#F: %17B T: %18B | R: %19 W: %20
InlineSetting=Color | #BarColor#
InlinePattern=.*#CRLF#.*#CRLF#.*#CRLF#(.*)#CRLF#(.*)#CRLF#(.*)
InlineSetting2=Color | #BarColor#
InlinePattern2=\/
InlineSetting3=Color | #Accent#
InlinePattern3=C: (\/{[DriveCActual:0]}).*
InlineSetting4=Color | #Accent#
InlinePattern4=D: (\/{[DriveDActual:0]}).*
InlineSetting5=Color | #Accent#
InlinePattern5=E: (\/{[DriveEActual:0]}).*
InlineSetting6=Color | #Accent#
InlinePattern6=H: (\/{[DriveHActual:0]}).*
InlineSetting7=Color | #Accent#
InlinePattern7=Z: (\/{[DriveZActual:0]}).*
DynamicVariables=1
MeterStyle=Text

**Comment by Chuckle12345** [comment]
![2021-06-24 21_43_27-E__PortableApps_PortableApps_Rainmeter_Skins_Plainext_Main_Main ini](https://user-images.githubusercontent.com/86451981/123362035-ad281400-d535-11eb-9741-6048d8c43576.png)
![2021-06-24 21_44_04-E__PortableApps_PortableApps_Rainmeter_Skins_Plainext_Main_Main ini](https://user-images.githubusercontent.com/86451981/123362036-ad281400-d535-11eb-8d4f-b44f9ea1c2d2.png)

**Comment by EnhancedJax** [comment]
Hey! Thanks for using the skin. 
I've seem to fix the problem, try this code:

```
[ResourceGraphDrives]
Meter=String
Autoscale=1
MeasureName=DriveCFree
MeasureName2=DriveCTotal
MeasureName3=MeasureDriveCRead
MeasureName4=MeasureDriveCWrite
MeasureName5=DriveDFree
MeasureName6=DriveDTotal
MeasureName7=MeasureDriveDRead
MeasureName8=MeasureDriveDWrite
MeasureName9=DriveEFree
MeasureName10=DriveETotal
MeasureName11=MeasureDriveERead
MeasureName12=MeasureDriveEWrite
MeasureName13=DriveHFree
MeasureName14=DriveHTotal
MeasureName15=MeasureDriveHRead
MeasureName16=MeasureDriveHWrite
MeasureName17=DriveZFree
MeasureName18=DriveZTotal
MeasureName19=MeasureDriveZRead
MeasureName20=MeasureDriveZWrite
;Text=C: //////////////////// [DriveCPercent:1]%#CRLF#F: %1B T: %2B | R: %3 W: %4#CRLF#D: //////////////////// [DriveDPercent:1]%#CRLF#F: %5B T: %6B | R: %7 W: %8
Text=C: //////////////////// [DriveCPercent:1]% (Windows)#CRLF#F: %1B T: %2B | R: %3 W: %4#CRLF#D: //////////////////// [DriveDPercent:1]% (Virtual)#CRLF#F: %5B T: %6B | R: %7 W: %8#CRLF#E: //////////////////// [DriveEPercent:1]% (UHaul)#CRLF#F: %9B T: %10B | R: %11 W: %12#CRLF#H: //////////////////// [DriveHPercent:1]% (RAMDisk)#CRLF#F: %13B T: %14B | R: %15 W: %16#CRLF#Z: //////////////////// [DriveZPercent:1]% (NAS)#CRLF#F: %17B T: %18B | R: %19 W: %20
InlineSetting=Color | #BarColor#
InlinePattern=/
InlineSetting2=Color | #Accent#
InlinePattern2=C: (/{[DriveCActual:0]}).*
InlineSetting3=Color | #Accent#
InlinePattern3=D: (/{[DriveDActual:0]}).*
InlineSetting4=Color | #Accent#
InlinePattern4=E: (/{[DriveEActual:0]}).*
InlineSetting5=Color | #Accent#
InlinePattern5=H: (/{[DriveHActual:0]}).*
InlineSetting6=Color | #Accent#
InlinePattern6=Z: (/{[DriveZActual:0]}).*
DynamicVariables=1
MeterStyle=Text
```

**Comment by Chuckle12345** [comment]
So you know I am going to ask.  I saw those 2 InlineSetting/Pattern lines, but couldn't match them up to anything in the skin.  What purpose did they serve?  They were there in the original file.  Thanks for the help.  I love this skin.

ce

**Comment by Chuckle12345** [comment]
Fixed
