### ISSUE TITLE
Sample Using CoreTemp to show/graph CPU.MaxTemperature 

### ISSUE THREAD

**Issue by Chuckle12345** [EnhancedJax/Plainext#3]
I'd like to display the CPU.MaxTemperature, using CoreTemp,  as a usage graph similar to CPU.Usage.  I'd like to configure the Max temp for the graph.   I have taken a quick look at it, and will invest more time this weekend.  I thought I would ask as you may have already done it.  Thanks. 

ce

**Comment by Chuckle12345** [comment]
I got it to work as a line entry using your examples for config of CoreTemp.  A line meter would be nice like the CPU or RAM entries.  Thanks.

MaxTemperature: 55 (50°C-85°C Normal Range)

ce

**Comment by EnhancedJax** [comment]
Hey there, sorry I didn't make the CPU temperature for the skin, and currently have to plans on doing so. Feel free to change whatever you want though!
😊

**Comment by Chuckle12345** [comment]
I will try and get it to work.  If I do I will send you the config so you add it to the example code.

**Comment by Chuckle12345** [comment]
Fixed
