### ISSUE TITLE
Enable customization of storage media for monitoring

### ISSUE THREAD

**Issue by pulverize** [EnhancedJax/Plainext#4]
Given that not all users have two storage drives lettered C and D, please enable users to define storage drives for monitoring in a central location (e.g., the vars file).

I'd love to be able to define "disk1=C: disk2=D: disk3=T:" centrally so that I don't have to modify inline patterns in multiple files. Suggest breaking up the ResourceGraphDrives meter into a meter per drive to improve configurability and reusability. Hard to track 10+ MeasureName settings on a single element.

**Comment by EnhancedJax** [comment]
Okay 👌
