### ISSUE TITLE
Upgrade deprecated PerfMon dependency

### ISSUE THREAD

**Issue by pulverize** [EnhancedJax/Plainext#5]
Given that PerfMon.dll was [deprecated in April 2018](https://docs.rainmeter.net/history/), convert dependency to [UsageMonitor](https://docs.rainmeter.net/manual-beta/plugins/usagemonitor/).

PerfMon is causing "run at startup" to result in a Rainmeter crash for me.

Edit: The PerfMon crash was fixed in the new release, so not urgent. Still, 3 years of dev and new functionality over in UsageMonitor

**Comment by EnhancedJax** [comment]
Noted. Thanks 😊
