### ISSUE TITLE
An update was released

### ISSUE THREAD

**Issue by Chuckle12345** [EnhancedJax/Plainext#6]
I appears an update was released.  How do I get passed, or disable the update graphic.  I don't have time to redo all of my customizations but want my skin back.  At least until i have time to figure out what you did, and add my customizations.  Thanks.

ce

**Comment by EnhancedJax** [comment]
I am not sure what you changed so I can't give a full solution, if you have
not updated yet and appears that it tells you to update, remove Compare
measure from the skin. If you updated, unfortunately there is no way to get
the skin back

**Comment by Chuckle12345** [comment]
I always make a backup.  I have the old modified skin.  I just need to get rid of that Update available ascii message.  I will upgrade tonight, but hate seeing that white message on my desktop.  I will look for Compare in the VSCode workspace.

**Comment by Chuckle12345** [comment]
Thanks that worked.  I just commented out the Compare->IfNotMatchAction line.  I will update to the new version tonight.  Thanks again for this nice skin.

**Comment by Chuckle12345** [comment]
Fixed
