### ISSUE TITLE
Microsoft removed the WMIC tool from Windows 11 Dev builds

### ISSUE THREAD

**Issue by 1ucay** [EnhancedJax/Plainext#8]
Hello sir,

I have problem with wmic command in your Plainext. Widget dont show GPU a MBD anymore.
https://winaero.com/microsoft-removed-the-wmic-tool-from-windows-11-dev-builds/

So workaround is switching to powershell, which working for me ok.

[MeasureGPUName]
Measure=Plugin
Plugin=RunCommand
Program=powershell.exe
Parameter=Get-WmiObject Win32_VideoController | Select-Object -Expand Name

[MeasureMotherboardname]
Measure=Plugin
Plugin=RunCommand
Program=powershell.exe
Parameter=Get-WmiObject Win32_BaseBoard | Select-Object -Expand Product

**Comment by EnhancedJax** [comment]
Thankyou! I'll update the skin later. 👍
